Repository SouJunior/mentores-frontend, pull requests merged in 2023-05, with the labels that each got.

#13 Develop
  next.config.js
  package-lock.json
  package.json
  public/favicon.ico
  public/icons/EmailDefault.svg
  public/icons/EmailHover.svg
  public/icons/EmailSelected.svg
  public/icons/EyeClosed.svg
  public/icons/EyeDefault.svg
  public/icons/Fecha.svg
  public/icons/Fecha1.svg
  public/icons/Group.svg
  public/icons/Lupa.svg
  public/icons/SenhaDefault.svg
  public/icons/SenhaHover.svg
  public/icons/SenhaSelected.svg
  public/icons/thirteen.svg
  public/images/BackgroundFigures.svg
  public/images/BackgroundLogin.svg
  public/images/fundoModal.svg
  public/images/ilustracao.svg
  public/images/modal.svg
  public/logos/LogoSJ.svg
  public/logos/LogoSouJunior.svg
  public/next.svg
  public/vercel.svg
  src/components/InputEmail/inputEmail.module.scss
  src/components/atoms/ButtonPrimary/index.jsx
  src/components/atoms/ButtonPrimary/style.js
  src/components/atoms/ButtonSecondary/index.jsx
  src/components/atoms/ButtonSecondary/style.js
  src/components/atoms/Checkbox/checkbox.jsx
  src/components/atoms/Checkbox/checkbox.module.scss
  src/components/atoms/FormCard/formCard.jsx
  src/components/atoms/FormCard/formCard.module.scss
  src/components/atoms/InputEmail/inputEmail.jsx
  src/components/atoms/InputEmail/inputEmail.module.scss
  src/components/atoms/InputSenha/inputSenha.jsx
  src/components/atoms/InputSenha/inputSenha.module.scss
  src/components/atoms/PersonTitle/index.jsx
  src/components/atoms/PersonTitle/style.js
  src/components/molecules/Header/index.jsx
  src/components/molecules/Header/style.js
  src/components/organisms/HeroSection/index.jsx
  src/components/organisms/HeroSection/style.js
  src/pages/HomePage/index.jsx
  src/pages/_app.js
  src/pages/_app.jsx
  src/pages/_document.js
  src/pages/_document.jsx
  src/pages/index.jsx
  src/pages/login/index.jsx
  src/pages/login/login.module.scss
  src/styles/GlobalStyle.jsx
  src/styles/animations.js
  src/styles/globals.scss
  src/styles/theme.js
Labels: feature

#17 Home animation
  src/components/atoms/FormCard/formCard.module.scss
  src/components/atoms/InputSenha/EyeComponent.jsx
  src/components/atoms/InputSenha/inputSenha.jsx
  src/components/atoms/PersonTitle/index.jsx
  src/components/atoms/PersonTitle/style.js
  src/components/organisms/HeroSection/index.jsx
  src/components/organisms/HeroSection/style.js
  src/pages/LoginPage/style.js
  src/pages/_app.jsx
  src/pages/_document.jsx
  src/styles/animations.js
Labels: feature, frontend

#20 login modification
  public/images/loading.svg
  public/images/loadingGif.gif
  src/components/atoms/Checkbox/checkbox.jsx
  src/components/atoms/Checkbox/checkbox.module.scss
  src/components/atoms/Checkbox/style.js
  src/components/atoms/FormCard/formCard.jsx
  src/components/atoms/FormCard/formCard.module.scss
  src/components/atoms/InputSenha/EyeComponent.jsx
  src/components/atoms/InputSenha/style.js
  src/pages/LoginPage/style.js
Labels: feature, frontend

#21 Develop
  public/images/loading.svg
  public/images/loadingGif.gif
  src/components/atoms/Checkbox/checkbox.jsx
  src/components/atoms/Checkbox/checkbox.module.scss
  src/components/atoms/Checkbox/style.js
  src/components/atoms/FormCard/formCard.jsx
  src/components/atoms/FormCard/formCard.module.scss
  src/components/atoms/InputSenha/EyeComponent.jsx
  src/components/atoms/InputSenha/style.js
  src/components/atoms/PersonTitle/index.jsx
  src/components/atoms/PersonTitle/style.js
  src/components/molecules/Header/index.jsx
  src/components/organisms/HeroSection/index.jsx
  src/components/organisms/HeroSection/style.js
  src/pages/LoginPage/style.js
  src/pages/_app.jsx
  src/pages/_document.jsx
  src/styles/animations.js
Labels: feature, frontend

#22 alteration Link
  src/components/atoms/FormCard/formCard.jsx
Labels: feature, frontend

#23 Develop
  src/components/atoms/FormCard/formCard.jsx
Labels: feature, frontend

#24 alteration Link
  src/components/molecules/Header/index.jsx
Labels: feature, frontend

#25 alteration
  src/components/molecules/Header/index.jsx
Labels: feature, frontend

#26 alteration
  src/components/molecules/Header/index.jsx
Labels: feature, frontend

#27 normalize
  package-lock.json
  package.json
  src/components/atoms/FormButtonConcluir/formButtonConcluir.jsx
  src/components/atoms/FormButtonDescarta/formButtonDescarta.jsx
  src/components/atoms/FormCadastro/FormInput.jsx
  src/components/atoms/FormCadastro/style.js
  src/components/atoms/FormCard/formCard.jsx
  src/components/atoms/FormDate/FormDate.module.scss
  src/components/atoms/FormEmail/FormEmail.module.scss
  src/components/atoms/FormEmail/formEmail.jsx
  src/components/atoms/FormEmailRevalidation/FormEmailRevalidation.module.scss
  src/components/atoms/FormEmailRevalidation/formEmailRevalidation.jsx
  src/components/atoms/FormInput/Cadastro.module.scss
  src/components/atoms/FormInput/FormInput.jsx
  src/components/atoms/FormNome/FormNome.module.scss
  src/components/atoms/FormNome/formNome.jsx
  src/components/atoms/FormPasswordRevalidation/FormPasswordRevalidation.module.scss
  src/components/atoms/FormPasswordRevalidation/formPasswordRevalidation.jsx
  src/components/atoms/FormSenha/FormSenha.module.scss
  src/components/atoms/FormSenha/formSenha.jsx
  src/components/atoms/InputEmail/inputEmail.jsx
  src/components/atoms/InputForm/index.jsx
  src/components/atoms/InputForm/style.js
  src/components/atoms/InputSenha/inputSenha.jsx
  src/components/molecules/Header/index.jsx
  src/components/organisms/HeroSection/index.jsx
  src/pages/Cadastro/Cadastro.module.scss
  src/pages/Cadastro/index.jsx
  src/pages/LoginPage/index.jsx
  src/pages/_app.jsx
  src/styles/GlobalStyle.jsx
  src/styles/pages/CadastroStyles.js
  src/styles/pages/LoginStyles.js
  src/styles/theme.js
Labels: duplicate, frontend

#28 fix: :bug: link para cadastro
  src/components/molecules/Header/index.jsx
Labels: bug, frontend

#30 Template email register
  templateEmailRegister/assets/garotaAcenando.png
  templateEmailRegister/index.html
Labels: feature, frontend

#32 fix: :lipstick: link para onboarding
  src/components/molecules/Header/index.jsx
  src/components/organisms/Onboarding/index.jsx
  src/pages/_app.jsx
  src/styles/GlobalStyle.jsx
Labels: bug, frontend

#34 feat: :sparkles: tela de login finalizada
  package-lock.json
  package.json
  public/icons/EmailDefault.svg
  public/icons/EmailHover.svg
  public/images/loadingGif.gif
  src/components/atoms/Button/index.jsx
  src/components/atoms/Button/style.js
  src/components/atoms/Checkbox/checkbox.jsx
  src/components/atoms/Checkbox/index.jsx
  src/components/atoms/Checkbox/style.js
  src/components/atoms/FormCadastro/FormInput.jsx
  src/components/atoms/FormCard/formCard.jsx
  src/components/atoms/FormCard/formCard.module.scss
  src/components/atoms/InputEmail/inputEmail.jsx
  src/components/atoms/InputEmail/style.js
  src/components/atoms/InputLogin/EyeComponent.jsx
  src/components/atoms/InputLogin/index.jsx
  src/components/atoms/InputLogin/style.js
  src/components/atoms/InputRegister/index.jsx
  src/components/atoms/InputRegister/style.js
  src/components/atoms/InputSenha/inputSenha.jsx
  src/components/atoms/InputSenha/style.js
  src/components/molecules/FormLogin/index.jsx
  src/components/molecules/FormLogin/style.js
  src/components/molecules/Header/index.jsx
  src/pages/LoginPage/index.jsx
  src/styles/theme.js
Labels: feature, help wanted, frontend
