Repository SouJunior/mentores-frontend, pull requests merged in 2023-06, with the labels that each got.

#37 Feat form validation
  package-lock.json
  package.json
  src/components/atoms/FormCadastro/FormInput.jsx
  src/components/atoms/FormCadastro/style.js
  src/components/atoms/InputRegister/index.jsx
  src/components/atoms/InputRegister/label.jsx
  src/components/atoms/InputRegister/style.js
  src/utils/registerSchema.js
Labels: feature, frontend

#44 Feat disable botao/open modal
  src/components/atoms/FormButtonConcluir/FormButtonConcluir.module.scss
  src/components/atoms/FormButtonConcluir/formButtonConcluir.jsx
  src/components/atoms/FormCadastro/FormInput.jsx
  src/components/atoms/RadioAgree/index.jsx
  src/components/atoms/RadioAgree/style.js
  src/utils/modalStyles.js
Labels: feature, frontend

#46 feat: :sparkles: ajuste de template para HTML4
  Templates/EmailRegister/assets/garotaAcenando.png
  Templates/EmailRegister/index.html
  templateEmailRegister/index.html
Labels: feature, frontend

#45 fix: :lipstick: mudança no estilo dos inputs
  src/components/molecules/FormLogin/index.jsx
Labels: bug, frontend

#42 feat: criação do component de modal
  package-lock.json
  package.json
  src/components/atoms/FormCadastro/FormInput.jsx
  src/components/atoms/Modal/index.jsx
  src/components/atoms/Modal/style.js
Labels: feature, frontend

#60 Development
  src/components/atoms/FormRegister/FormRegister.jsx
  src/components/atoms/FormRegister/style.js
  src/components/atoms/Modal/index.jsx
  src/components/atoms/Modal/style.js
  src/pages/Cadastro/index.jsx
  src/styles/theme.js
Labels: feature, frontend

#63 58 botão cancelar register
  src/components/atoms/Button/index.jsx
  src/components/atoms/Button/style.js
  src/components/atoms/FormButtonDescarta/FormButtonDescarta.module.scss
  src/components/atoms/FormButtonDescarta/formButtonDescarta.jsx
  src/components/atoms/FormRegister/FormRegister.jsx
  src/components/atoms/FormRegister/style.js
  src/components/atoms/InputForm/style.js
  src/components/atoms/InputLogin/style.js
  src/styles/pages/CadastroStyles.js
Labels: feature, frontend

#64 Feat modal email
  public/images/ConfirmEmail.png
  src/components/atoms/FormRegister/FormRegister.jsx
  src/components/molecules/ModalEmail/index.jsx
  src/components/molecules/ModalEmail/style.js
Labels: feature, frontend

#65 Fix - btn concluir
  src/components/atoms/Button/index.jsx
  src/components/atoms/Button/style.js
  src/components/atoms/FormButtonConcluir/FormButtonConcluir.module.scss
  src/components/atoms/FormButtonConcluir/formButtonConcluir.jsx
  src/components/atoms/FormRegister/FormRegister.jsx
  src/components/molecules/ModalEmail/index.jsx
  src/components/molecules/ModalEmail/style.js
  src/utils/registerSchema.js
Labels: frontend, Fix

#67 Feat/66 implementar modal de cancelamento
  src/components/atoms/Button/index.jsx
  src/components/atoms/Button/style.js
  src/components/atoms/ModalComponent/index.jsx
  src/components/atoms/ModalComponent/style.js
  src/components/atoms/RadioAgree/index.jsx
  src/components/atoms/RadioAgree/style.js
  src/components/molecules/FormRegister/FormRegister.jsx
  src/components/molecules/ModalCancel/index.jsx
  src/components/molecules/ModalCancel/style.js
  src/components/molecules/ModalEmail/index.jsx
  src/styles/theme.js
Labels: feature, frontend

#70 Fix modal terms politicas
  src/components/molecules/FormRegister/FormRegister.jsx
  src/components/molecules/ModalPoliticas/index.jsx
  src/components/molecules/ModalPoliticas/style.js
  src/components/molecules/ModalTerms/index.jsx
  src/components/molecules/ModalTerms/style.js
Labels: frontend, Fix

#72 feat: criação do CardComponent
  src/components/atoms/CardComponent/index.jsx
  src/components/molecules/FormRegister/FormRegister.jsx
Labels: feature, frontend

#76 feat: :sparkles: criação e implementação do componente footer
  public/images/homepage/footer/discord.png
  public/images/homepage/footer/face.png
  public/images/homepage/footer/github.png
  public/images/homepage/footer/insta.png
  public/images/homepage/footer/linkedin.png
  public/images/homepage/footer/telegram.png
  public/images/homepage/footer/twitch.png
  public/images/homepage/footer/twitter.png
  public/images/homepage/footer/youtube.png
  public/images/homepage/heroSection/mentor1-png.png
  public/images/homepage/heroSection/mentor2-png.png
  public/images/homepage/heroSection/mentor3-png.png
  public/logos/LogoSouJunior-Black.png
  src/components/molecules/Footer/index.jsx
  src/components/molecules/Footer/style.js
  src/components/molecules/Header/index.jsx
  src/components/molecules/ListItemsHero/index.jsx
  src/pages/HomePage/index.jsx
Labels: feature, frontend

#77 Feat/card mentor
  public/images/vanessa.png
  src/components/atoms/CardComponent/index.jsx
  src/components/molecules/CardMentor/index.jsx
  src/components/molecules/CardMentor/style.js
  src/components/molecules/FormRegister/FormRegister.jsx
  src/components/organisms/HeroSection/index.jsx
Labels: feature, frontend

#78 feat: criação do slider_component e da sessão Mentors
  package-lock.json
  package.json
  public/images/vinicius.png
  public/images/wanderson.png
  src/components/atoms/SliderComponent/index.jsx
  src/components/atoms/SliderComponent/style.js
  src/components/molecules/CardMentor/style.js
  src/components/organisms/HeroSection/index.jsx
  src/components/organisms/Mentors/index.jsx
  src/components/organisms/Mentors/style.js
  src/pages/HomePage/index.jsx
Labels: feature, frontend

#82 Feat tooltip
  public/icons/Info.png
  src/components/atoms/InfoTooltip/index.jsx
  src/components/atoms/InfoTooltip/style.js
  src/components/molecules/FormRegister/FormRegister.jsx
Labels: feature, frontend

#84 Feat/mockup mentores
  public/icons/Info.png
  public/images/homepage/mentores/gustavo.png
  public/images/homepage/mentores/julio.jpeg
  public/images/homepage/mentores/leonardo.png
  public/images/homepage/mentores/mateus.jpg
  public/images/homepage/mentores/rarielly.jpg
  public/images/homepage/mentores/wanderson.png
  src/components/atoms/InfoTooltip/index.jsx
  src/components/atoms/InfoTooltip/style.js
  src/components/molecules/CardMentor/index.jsx
  src/components/molecules/Footer/index.jsx
  src/components/molecules/FormRegister/FormRegister.jsx
  src/components/molecules/Header/index.jsx
  src/components/molecules/ModalEmail/index.jsx
  src/components/organisms/MentorSection/index.jsx
  src/components/organisms/MentorSection/style.js
  src/components/organisms/Mentors/index.jsx
  src/mockups/mentores.js
  src/pages/HomePage/index.jsx
Labels: feature, frontend

#87 feat: :sparkles: criação de seção depoimentos com car e slider
  public/images/homepage/mentores/gustavo.png
  public/images/homepage/mentores/julio.jpeg
  public/images/homepage/mentores/leonardo.png
  public/images/homepage/mentores/mateus.jpg
  public/images/homepage/mentores/rarielly.jpg
  public/images/homepage/mentores/wanderson.png
  src/components/atoms/Button/style.js
  src/components/atoms/CardOnboarding/index.jsx
  src/components/atoms/CardOnboarding/style.js
  src/components/atoms/SliderComponent/index.jsx
  src/components/molecules/CardDepo/index.jsx
  src/components/molecules/CardDepo/style.js
  src/components/molecules/CardMentor/index.jsx
  src/components/molecules/Footer/index.jsx
  src/components/molecules/Header/index.jsx
  src/components/molecules/ListCardsOnboarding/index.jsx
  src/components/molecules/ListCardsOnboarding/style.js
  src/components/organisms/DepoSection/index.jsx
  src/components/organisms/DepoSection/style.js
  src/components/organisms/MentorSection/index.jsx
  src/components/organisms/MentorSection/style.js
  src/components/organisms/Mentors/index.jsx
  src/components/organisms/Onboarding/index.jsx
  src/mockups/mentores.js
  src/pages/HomePage/index.jsx
Labels: feature, frontend

#90 Development
  src/components/atoms/Button/style.js
  src/components/atoms/CardOnboarding/index.jsx
  src/components/atoms/CardOnboarding/style.js
  src/components/atoms/SliderComponent/index.jsx
  src/components/molecules/CardDepo/index.jsx
  src/components/molecules/CardDepo/style.js
  src/components/molecules/ListCardsOnboarding/index.jsx
  src/components/molecules/ListCardsOnboarding/style.js
  src/components/organisms/DepoSection/index.jsx
  src/components/organisms/DepoSection/style.js
  src/components/organisms/MentorSection/index.jsx
  src/components/organisms/Onboarding/index.jsx
  src/pages/HomePage/index.jsx
Labels: feature, frontend

#91 Development
  next.config.js
  package-lock.json
  package.json
  src/components/molecules/FormLogin/index.jsx
  src/components/molecules/FormLogin/style.js
  src/components/molecules/FormRegister/FormRegister.jsx
  src/utils/modalStyles.js
  src/utils/registerSchema.js
Labels: feature, frontend, Fix

#93 Feat eye global
  src/components/atoms/EyeComponent/index.jsx
  src/components/atoms/EyeComponent/style.js
  src/components/atoms/InputLogin/EyeComponent.jsx
  src/components/atoms/InputLogin/index.jsx
  src/components/molecules/FormRegister/index.jsx
Labels: feature, frontend

#94 Development
  src/components/atoms/EyeComponent/index.jsx
  src/components/atoms/EyeComponent/style.js
  src/components/atoms/InputLogin/EyeComponent.jsx
  src/components/atoms/InputLogin/index.jsx
  src/components/molecules/FormRegister/index.jsx
Labels: feature, frontend
